# Site settings
title: "CS142: Web Applications"

# Build settings
markdown: kramdown

# Navigation settings
navigation:
- text: Home
  url: /
- text: Class Info
  url: /info.html
- text: Lectures
  url: /lectures.html
- text: Projects
  url: /projects.html
- text: Staff
  url: /staff.html

# Basic information for homepage
basic:
- title: Lectures
  text: MWF 10:30-11:20am at 420-040
- title: Instructor
  text: <a href="http://www.stanford.edu/~mendel/">Mendel Rosenblum</a>
- title: Sections
  text: TBA
- title: Midterm
  text: TBA
- title: Final
  text: TBA
- title: Contact Staff
  text: cs142-spr1516-staff@lists

# Instructor details
instructor:
- name: Mendel Rosenblum
  photo: mendel.jpg
  email: mendel@cs

# Course Assistant details
cas:
- name: Raymond Luong
  photo: raymond.png
  email: rayluong@
- name: Raymond Luong
  photo: raymond.png
  email: rayluong@
- name: Raymond Luong
  photo: raymond.png
  email: rayluong@
- name: Raymond Luong
  photo: raymond.png
  email: rayluong@
- name: Raymond Luong
  photo: raymond.png
  email: rayluong@
- name: Raymond Luong
  photo: raymond.png
  email: rayluong@